data_collection_task:
  description: "Read customer transactions, profiles, and sentiment data to create a comprehensive user profile."
  agent: customer_profile_aggregator
  expected_output: A json file named customer_data.json

sentiment_analysis_task:
  description: "Analyze sentiment scores, financial needs, and behavioral patterns."
  agent: sentiment_behavior_analyst
  input: customer_data.json
  expected_output: A json file enriched_customer_data.json that combines input with sentiment and behavour analysis information

recommendation_task:
  description: "Generate top 5 financial product recommendations based on customer insights."
  agent: recommendation_engine
  input: enriched_customer_data.json
  expected_output: A json file recommendations.json that should contain customer infor along with recommended products and the rationale behind it
